name: sync_storage
description: Sync storage enables simple database synchronization.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.4.8

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  scoped_logger: ^0.1.0
  rxdart: ^0.27.3
  objectid: ^2.0.0
  meta: ^1.8.0
  collection: ^1.16.0

dev_dependencies:
  mockito: ^5.0.17
  build_runner: ^2.1.7
  test: any
