name: sync_storage
description: Sync storage enables simple database synchronization.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.2.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  connectivity: ^2.0.2
  objectid: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  test: any

flutter:
  uses-material-design: true
