name: Checks
on:
  release:
    types: [created]
  push:
    branches:
      - master

jobs:
  checks:
    name: Analyzer and unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.2.1
        with:
          channel: 'stable'
      - name: Getting packages
        run: flutter pub get
      - name: analyzis
        run: flutter analyze .
      - name: tests
        run: flutter test
